name: Main Branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '**.js' # Trigger on changes to JavaScript files
concurrency:
  group: 'ci-${{ github.ref }}' # 
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Print msg
        run: echo "hi"
