name: Main Branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '**.js' # Trigger on changes to JavaScript files
concurrency:
  group: 'ci-${{ github.ref }}' # 
  cancel-in-progress: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Print msg
        run: echo "hi"
  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        nodeVersion: [21, 22]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: Run Tests
        run: |
          echo "Running tests on Node.js version ${{ matrix.nodeVersion }}"
          node -v
  # golangci-lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4
  #     - name: Setup Go
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: '1.21'
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v3
  #       with:
  #         version: latest